##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.10.0-B28] date: [Thu Sep 10 11:18:39 CST 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = multi-axis-canopen-master


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
APP/main.c \
framework/Core/Src/stm32f4xx_it.c \
framework/Core/Src/stm32f4xx_hal_msp.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
framework/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
framework/Core/Src/system_stm32f4xx.c \
framework/Core/Src/sysmem.c \
framework/Core/Src/syscalls.c \
framework/Core/Src/gpio.c \
framework/Core/Src/can.c \
framework/Core/Src/usart.c \
framework/BSP/bsp_uart.c \
framework/canopen/CANopenNode/CANopen.c \
framework/canopen/CANopenNode/301/CO_Emergency.c \
framework/canopen/CANopenNode/301/CO_fifo.c \
framework/canopen/CANopenNode/301/CO_HBconsumer.c \
framework/canopen/CANopenNode/301/CO_NMT_Heartbeat.c \
framework/canopen/CANopenNode/301/CO_Node_Guarding.c \
framework/canopen/CANopenNode/301/CO_ODinterface.c \
framework/canopen/CANopenNode/301/CO_PDO.c \
framework/canopen/CANopenNode/301/CO_SDOclient.c \
framework/canopen/CANopenNode/301/CO_SDOserver.c \
framework/canopen/CANopenNode/301/CO_SYNC.c \
framework/canopen/CANopenNode/301/CO_TIME.c \
framework/canopen/CANopenNode/301/crc16-ccitt.c \
framework/canopen/CANopenNode/303/CO_LEDs.c \
framework/canopen/CANopenNode/304/CO_GFC.c \
framework/canopen/CANopenNode/304/CO_SRDO.c \
framework/canopen/CANopenNode/305/CO_LSSmaster.c \
framework/canopen/CANopenNode/305/CO_LSSslave.c \
framework/canopen/CANopenNode/309/CO_gateway_ascii.c \
framework/canopen/CANopenNode/storage/CO_storage.c \
framework/canopen/CANopenNode/storage/CO_storageEeprom.c \
framework/canopen/CANopenNode/extra/CO_trace.c \
framework/canopen/OD/OD.c \
framework/canopen/canopen_app.c \
framework/canopen/port/CO_driver_STM32.c

# ASM sources
ASM_SOURCES =  \
startup_stm32f407xx.s

# ASMM sources
ASMM_SOURCES = 



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F407xx \
-DCO_DRIVER_CUSTOM


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IAPP \
-Iframework/Core/Inc \
-Iframework/BSP \
-Iframework/canopen \
-Iframework/canopen/CANopenNode \
-Iframework/canopen/port \
-Iframework/canopen/OD \
-Iframework/Drivers/STM32F4xx_HAL_Driver/Inc \
-Iframework/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-Iframework/Drivers/CMSIS/Device/ST/STM32F4xx/Include \
-Iframework/Drivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F407xx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
